version: "3"
services:
  couchdb:
    image: couchdb
    ports:
      - "5984:5984"
    volumes:
      - "./couchdb/data:/opt/couchdb/data"

  lei-issuer:
    build: ./lei-issuer
    image: lei-issuer
    ports:
      - "8090:3000"
    volumes:
      - "./lei-issuer/public:/opt/app/public"
      - "./lei-issuer/views:/opt/app/views"
    environment:
      - DB_CONNECTION_STRING=http://couchdb:5984
      - DB_USERS=lei_issuer_db
      - LOG_LEVEL=debug
      - ACCOUNT_URL
      - AGENT_NAME=${LEI_ISSUER_AGENT_NAME}
      - AGENT_PASSWORD=${LEI_ISSUER_AGENT_PASSWORD}
      - FRIENDLY_NAME=LEI Issuer
      - AGENT_ADMIN_NAME
      - AGENT_ADMIN_PASSWORD
      - MY_URL=${LEI_ISSUER_URL}
      - CONNECTION_IMAGE_PROVIDER=none
      - CARD_IMAGE_RENDERING=none
      - ADMIN_API_USERNAME
      - ADMIN_API_PASSWORD
    links:
      - couchdb

  gleif:
    build: ./gleif
    image: gleif
    ports:
      - "8091:3000"
    volumes:
      - "./gleif/public:/opt/app/public"
      - "./gleif/views:/opt/app/views"
    environment:
      - DB_CONNECTION_STRING=http://couchdb:5984
      - DB_USERS=gleif_db
      - LOG_LEVEL=debug
      - ACCOUNT_URL
      - AGENT_NAME=${GLEIF_AGENT_NAME}
      - AGENT_PASSWORD=${GLEIF_AGENT_PASSWORD}
      - FRIENDLY_NAME=GLEIF
      - AGENT_ADMIN_NAME
      - AGENT_ADMIN_PASSWORD
      - MY_URL=${GLEIF_URL}
      - CONNECTION_IMAGE_PROVIDER=none
      - CARD_IMAGE_RENDERING=none
      - ADMIN_API_USERNAME
      - ADMIN_API_PASSWORD
    links:
      - couchdb

  acme:
    build: ./acme
    image: acme
    ports:
      - "8092:3000"
    volumes:
      - "./acme/public:/opt/app/public"
      - "./acme/views:/opt/app/views"
    environment:
      - DB_CONNECTION_STRING=http://couchdb:5984
      - DB_USERS=acme_db
      - LOG_LEVEL=debug
      - ACCOUNT_URL
      - AGENT_NAME=${ACME_AGENT_NAME}
      - AGENT_PASSWORD=${ACME_AGENT_PASSWORD}
      - FRIENDLY_NAME=Acme Company
      - AGENT_ADMIN_NAME
      - AGENT_ADMIN_PASSWORD
      - MY_URL=${ACME_URL}
      - CONNECTION_IMAGE_PROVIDER=none
      - CARD_IMAGE_RENDERING=none
      - ADMIN_API_USERNAME
      - ADMIN_API_PASSWORD
    links:
      - couchdb