version: "3"
services:
  tys-couchdb:
    image: couchdb
    ports:
      - "5984:5984"
    volumes:
      - "./couchdb/data:/opt/couchdb/data"
    environment:
      - 'COUCHDB_USER=${COUCHDB_USER_NAME}'
      - 'COUCHDB_PASSWORD=${COUCHDB_USER_PASSWORD}'

  lei-issuer:
    build: ./lei-issuer
    image: lei-issuer
    ports:
      - "8190:3000"
    volumes:
      - "./lei-issuer/public:/opt/app/public"
      - "./lei-issuer/views:/opt/app/views"
    environment:
      - DB_CONNECTION_STRING=http://${COUCHDB_USER_NAME}:${COUCHDB_USER_PASSWORD}@tys-couchdb:5984
      - DB_USERS=lei_issuer_db
      - LOG_LEVEL=debug
      - ACCOUNT_URL
      - AGENT_NAME=${LEI_ISSUER_AGENT_NAME}
      - AGENT_PASSWORD=${LEI_ISSUER_AGENT_PASSWORD}
      - FRIENDLY_NAME=LEI Issuer
      - AGENT_ADMIN_NAME
      - AGENT_ADMIN_PASSWORD
      - MY_URL=${LEI_ISSUER_URL}
      - CONNECTION_IMAGE_PROVIDER=static
      - CARD_IMAGE_RENDERING=none
      - ADMIN_API_USERNAME
      - ADMIN_API_PASSWORD
    links:
      - tys-couchdb

  gleif:
    build: ./gleif
    image: gleif
    ports:
      - "8191:3000"
    volumes:
      - "./gleif/public:/opt/app/public"
      - "./gleif/views:/opt/app/views"
    environment:
      - DB_CONNECTION_STRING=http://${COUCHDB_USER_NAME}:${COUCHDB_USER_PASSWORD}@tys-couchdb:5984
      - DB_USERS=gleif_db
      - LOG_LEVEL=debug
      - ACCOUNT_URL
      - AGENT_NAME=${GLEIF_AGENT_NAME}
      - AGENT_PASSWORD=${GLEIF_AGENT_PASSWORD}
      - FRIENDLY_NAME=GLEIF
      - AGENT_ADMIN_NAME
      - AGENT_ADMIN_PASSWORD
      - MY_URL=${GLEIF_URL}
      - CONNECTION_IMAGE_PROVIDER=static
      - CARD_IMAGE_RENDERING=none
      - ADMIN_API_USERNAME
      - ADMIN_API_PASSWORD
    links:
      - tys-couchdb

  acme:
    build: ./acme
    image: acme
    ports:
      - "8192:3000"
    volumes:
      - "./acme/public:/opt/app/public"
      - "./acme/views:/opt/app/views"
    environment:
      - DB_CONNECTION_STRING=http://${COUCHDB_USER_NAME}:${COUCHDB_USER_PASSWORD}@tys-couchdb:5984
      - DB_USERS=acme_db
      - LOG_LEVEL=debug
      - ACCOUNT_URL
      - AGENT_NAME=${ACME_AGENT_NAME}
      - AGENT_PASSWORD=${ACME_AGENT_PASSWORD}
      - FRIENDLY_NAME=ACME
      - AGENT_ADMIN_NAME
      - AGENT_ADMIN_PASSWORD
      - MY_URL=${ACME_URL}
      - CONNECTION_IMAGE_PROVIDER=static
      - CARD_IMAGE_RENDERING=none
      - ADMIN_API_USERNAME
      - ADMIN_API_PASSWORD
    links:
      - tys-couchdb

  ift-founder:
    build: ./ift-founder
    image: ift-founder
    ports:
      - "8193:3000"
    volumes:
      - "./ift-founder/public:/opt/app/public"
      - "./ift-founder/views:/opt/app/views"
    environment:
      - DB_CONNECTION_STRING=http://${COUCHDB_USER_NAME}:${COUCHDB_USER_PASSWORD}@tys-couchdb:5984
      - DB_USERS=ift-founder_db
      - LOG_LEVEL=debug
      - ACCOUNT_URL
      - AGENT_NAME=${IFT_FOUNDER_AGENT_NAME}
      - AGENT_PASSWORD=${IFT_FOUNDER_AGENT_PASSWORD}
      - FRIENDLY_NAME=IFT Founder
      - AGENT_ADMIN_NAME
      - AGENT_ADMIN_PASSWORD
      - SIGNUP_GLEIF_ISSUER_AGENT=${GLEIF_AGENT_NAME}
      - SIGNUP_LEI_ISSUER_AGENT=${LEI_ISSUER_AGENT_NAME}
      - MY_URL=${IFT_FOUNDER_URL}
      - CONNECTION_IMAGE_PROVIDER=none
      - CARD_IMAGE_RENDERING=none
      - ADMIN_API_USERNAME
      - ADMIN_API_PASSWORD
    links:
      - tys-couchdb

  tys:
    build: ./tys
    image: tys
    ports:
      - "8194:3000"
    volumes:
      - "./tys/public:/opt/app/public"
      - "./tys/views:/opt/app/views"
    environment:
      - DB_CONNECTION_STRING=http://${COUCHDB_USER_NAME}:${COUCHDB_USER_PASSWORD}@tys-couchdb:5984
      - DB_USERS=tys_db
      - LOG_LEVEL=debug
      - ACCOUNT_URL
      - AGENT_NAME=${TYS_AGENT_NAME}
      - AGENT_PASSWORD=${TYS_AGENT_PASSWORD}
      - FRIENDLY_NAME=IBM Trust Your Supplier
      - AGENT_ADMIN_NAME
      - AGENT_ADMIN_PASSWORD
      - SIGNUP_GLEIF_ISSUER_AGENT=${GLEIF_AGENT_NAME}
      - SIGNUP_LEI_ISSUER_AGENT=${LEI_ISSUER_AGENT_NAME}
      - MY_URL=${TYS_URL}
      - CONNECTION_IMAGE_PROVIDER=static
      - CARD_IMAGE_RENDERING=none
      - ADMIN_API_USERNAME
      - ADMIN_API_PASSWORD
    links:
        - tys-couchdb

  ift-network:
    build: ./ift-network
    image: ift-network
    ports:
      - "8195:3000"
    volumes:
      - "./ift-network/public:/opt/app/public"
      - "./ift-network/views:/opt/app/views"
    environment:
      - DB_CONNECTION_STRING=http://${COUCHDB_USER_NAME}:${COUCHDB_USER_PASSWORD}@tys-couchdb:5984
      - DB_USERS=ift-network_db
      - LOG_LEVEL=debug
      - ACCOUNT_URL
      - AGENT_NAME=${IFT_NETWORK_AGENT_NAME}
      - AGENT_PASSWORD=${IFT_NETWORK_AGENT_PASSWORD}
      - FRIENDLY_NAME=IFT Network
      - AGENT_ADMIN_NAME
      - AGENT_ADMIN_PASSWORD
      - SIGNUP_TYS_ISSUER_AGENT=${TYS_AGENT_NAME}
      - SIGNUP_LEI_ISSUER_AGENT=${LEI_ISSUER_AGENT_NAME}
      - SIGNUP_IFT_FOUNDER_ISSUER_AGENT=${IFT_FOUNDER_AGENT_NAME}
      - MY_URL=${IFT_NETWORK_URL}
      - CONNECTION_IMAGE_PROVIDER=static
      - CARD_IMAGE_RENDERING=none
      - ADMIN_API_USERNAME
      - ADMIN_API_PASSWORD
    links:
        - tys-couchdb

  test:
    container_name: testtys
    image: testtys
    build:
      context: test_holder
    environment:
      - ACCOUNT_URL
      - GLEIF_AGENT_NAME
      - GLEIF_AGENT_PASSWORD
      - LEI_ISSUER_AGENT_NAME
      - LEI_ISSUER_AGENT_PASSWORD
      - TYS_AGENT_NAME
      - TYS_AGENT_PASSWORD
      - ACME_AGENT_NAME
      - ACME_AGENT_PASSWORD
      - IFT_FOUNDER_AGENT_NAME
      - IFT_FOUNDER_AGENT_PASSWORD
      - IFT_NETWORK_AGENT_NAME
      - IFT_NETWORK_AGENT_PASSWORD
      - CA_TEST_CLEANUP_ACCOUNTS
    command: node ${CA_TEST_NAME}.js
